# Generated by Django 3.1.4 on 2021-02-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('technology', models.CharField(choices=[('python', 'Python'), ('flutter', 'Flutter'), ('android', 'Android')], max_length=255)),
            ],
        ),
    ]
